version: 2.1

orbs:
  android: circleci/android@2.1.2
  flutter-orb: circleci/flutter@1.1.0
  ruby: circleci/ruby@1.8.0
  macos: circleci/macos@2.3.1

jobs:
  build:
    executor:
      name: android/android-machine
      tag: 2022.03.1
    steps:
      - checkout
      - flutter-orb/install_sdk_and_pub:
          cache-version: machine
          flutter_version: 2.10.3
      - android/create-avd:
          avd-name: flutter
          install: true
          system-image: system-images;android-29;default;x86
      - android/start-emulator:
          avd-name: flutter
          post-emulator-launch-assemble-command: 'flutter build apk --debug'
          restore-gradle-cache-find-args: ./android -name 'build.gradle'